version: "3.8"

services:
  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--appendfsync", "everysec",
      "--port", "6379",
      "--databases", "16",
      "--maxmemory", "1536mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
    networks:
      - nobreluminarias
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  nobreluminarias:
    external: true
    name: nobreluminarias
